version: "3.9"

services:
  dash:
    build: .
    container_name: dash-webapp
    ports:
      - "8050:8050"
    restart: unless-stopped
    environment:
      - DASH_SERVE_LOCALLY=1   # 필요시 dash 자산 로컬 서빙 강제
